<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LabDesk.SeedWork.Application\LabDesk.SeedWork.Application.csproj" />
    <ProjectReference Include="..\LabDesk.SeedWork.Domain\LabDesk.SeedWork.Domain.csproj" />
  </ItemGroup>

</Project>
